/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.knetikcloud.model;

import com.knetikcloud.model.ActionResource;
import com.knetikcloud.model.PredicateOperation;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class BreRule {
  
  @SerializedName("actions")
  private ActionResource actions = null;
  @SerializedName("condition")
  private PredicateOperation condition = null;
  @SerializedName("condition_text")
  private String conditionText = null;
  @SerializedName("description")
  private String description = null;
  @SerializedName("enabled")
  private Boolean enabled = null;
  @SerializedName("end_date")
  private Long endDate = null;
  @SerializedName("event_name")
  private String eventName = null;
  @SerializedName("id")
  private String id = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("sort")
  private Integer sort = null;
  @SerializedName("start_date")
  private Long startDate = null;
  @SerializedName("system_rule")
  private Boolean systemRule = null;

  /**
   * A list of actions to execute, and the mapping for their parameters, when the rule runs. Minimum 1
   **/
  @ApiModelProperty(required = true, value = "A list of actions to execute, and the mapping for their parameters, when the rule runs. Minimum 1")
  public ActionResource getActions() {
    return actions;
  }
  public void setActions(ActionResource actions) {
    this.actions = actions;
  }

  /**
   * A condition expression that must be met in a given event for the rule to run. Empty to always run
   **/
  @ApiModelProperty(value = "A condition expression that must be met in a given event for the rule to run. Empty to always run")
  public PredicateOperation getCondition() {
    return condition;
  }
  public void setCondition(PredicateOperation condition) {
    this.condition = condition;
  }

  /**
   * The condition as a readable string. Filled in by the system from the condition
   **/
  @ApiModelProperty(value = "The condition as a readable string. Filled in by the system from the condition")
  public String getConditionText() {
    return conditionText;
  }
  public void setConditionText(String conditionText) {
    this.conditionText = conditionText;
  }

  /**
   * The human readable description of the rule
   **/
  @ApiModelProperty(value = "The human readable description of the rule")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   * Whether the rule is enabled to run (in conjunction with dates). Default true
   **/
  @ApiModelProperty(value = "Whether the rule is enabled to run (in conjunction with dates). Default true")
  public Boolean getEnabled() {
    return enabled;
  }
  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  /**
   * The date the rule ceases to take effect, or null if never. Unix timestamp in seconds
   **/
  @ApiModelProperty(value = "The date the rule ceases to take effect, or null if never. Unix timestamp in seconds")
  public Long getEndDate() {
    return endDate;
  }
  public void setEndDate(Long endDate) {
    this.endDate = endDate;
  }

  /**
   * The event name of the trigger this rule runs for. Affects which parameters are available
   **/
  @ApiModelProperty(required = true, value = "The event name of the trigger this rule runs for. Affects which parameters are available")
  public String getEventName() {
    return eventName;
  }
  public void setEventName(String eventName) {
    this.eventName = eventName;
  }

  /**
   * The id of the rule for later references. If left null a random guid will be generated. Must be unique. Cannot be changed
   **/
  @ApiModelProperty(value = "The id of the rule for later references. If left null a random guid will be generated. Must be unique. Cannot be changed")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   * The human readable name of the rule
   **/
  @ApiModelProperty(required = true, value = "The human readable name of the rule")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   * Used to sort rules to control the order they run in. Larger numbered sort values run first.  Default 500
   **/
  @ApiModelProperty(value = "Used to sort rules to control the order they run in. Larger numbered sort values run first.  Default 500")
  public Integer getSort() {
    return sort;
  }
  public void setSort(Integer sort) {
    this.sort = sort;
  }

  /**
   * The date the rule begins to take effect, or null if always. Unix timestamp in seconds
   **/
  @ApiModelProperty(value = "The date the rule begins to take effect, or null if always. Unix timestamp in seconds")
  public Long getStartDate() {
    return startDate;
  }
  public void setStartDate(Long startDate) {
    this.startDate = startDate;
  }

  /**
   * Whether the rule is a default part of the system. System rules cannot be edited or deleted, but may be disabled
   **/
  @ApiModelProperty(value = "Whether the rule is a default part of the system. System rules cannot be edited or deleted, but may be disabled")
  public Boolean getSystemRule() {
    return systemRule;
  }
  public void setSystemRule(Boolean systemRule) {
    this.systemRule = systemRule;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BreRule breRule = (BreRule) o;
    return (this.actions == null ? breRule.actions == null : this.actions.equals(breRule.actions)) &&
        (this.condition == null ? breRule.condition == null : this.condition.equals(breRule.condition)) &&
        (this.conditionText == null ? breRule.conditionText == null : this.conditionText.equals(breRule.conditionText)) &&
        (this.description == null ? breRule.description == null : this.description.equals(breRule.description)) &&
        (this.enabled == null ? breRule.enabled == null : this.enabled.equals(breRule.enabled)) &&
        (this.endDate == null ? breRule.endDate == null : this.endDate.equals(breRule.endDate)) &&
        (this.eventName == null ? breRule.eventName == null : this.eventName.equals(breRule.eventName)) &&
        (this.id == null ? breRule.id == null : this.id.equals(breRule.id)) &&
        (this.name == null ? breRule.name == null : this.name.equals(breRule.name)) &&
        (this.sort == null ? breRule.sort == null : this.sort.equals(breRule.sort)) &&
        (this.startDate == null ? breRule.startDate == null : this.startDate.equals(breRule.startDate)) &&
        (this.systemRule == null ? breRule.systemRule == null : this.systemRule.equals(breRule.systemRule));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.actions == null ? 0: this.actions.hashCode());
    result = 31 * result + (this.condition == null ? 0: this.condition.hashCode());
    result = 31 * result + (this.conditionText == null ? 0: this.conditionText.hashCode());
    result = 31 * result + (this.description == null ? 0: this.description.hashCode());
    result = 31 * result + (this.enabled == null ? 0: this.enabled.hashCode());
    result = 31 * result + (this.endDate == null ? 0: this.endDate.hashCode());
    result = 31 * result + (this.eventName == null ? 0: this.eventName.hashCode());
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.sort == null ? 0: this.sort.hashCode());
    result = 31 * result + (this.startDate == null ? 0: this.startDate.hashCode());
    result = 31 * result + (this.systemRule == null ? 0: this.systemRule.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class BreRule {\n");
    
    sb.append("  actions: ").append(actions).append("\n");
    sb.append("  condition: ").append(condition).append("\n");
    sb.append("  conditionText: ").append(conditionText).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  enabled: ").append(enabled).append("\n");
    sb.append("  endDate: ").append(endDate).append("\n");
    sb.append("  eventName: ").append(eventName).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  sort: ").append(sort).append("\n");
    sb.append("  startDate: ").append(startDate).append("\n");
    sb.append("  systemRule: ").append(systemRule).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
