/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.knetikcloud.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class CartShippingOption {
  
  @SerializedName("currency_code")
  private String currencyCode = null;
  @SerializedName("description")
  private String description = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("original_price")
  private Double originalPrice = null;
  @SerializedName("price")
  private Double price = null;
  @SerializedName("shipping_item_id")
  private Integer shippingItemId = null;
  @SerializedName("sku")
  private String sku = null;
  @SerializedName("taxable")
  private Boolean taxable = null;
  @SerializedName("vendor_id")
  private Integer vendorId = null;
  @SerializedName("vendor_name")
  private String vendorName = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCurrencyCode() {
    return currencyCode;
  }
  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getOriginalPrice() {
    return originalPrice;
  }
  public void setOriginalPrice(Double originalPrice) {
    this.originalPrice = originalPrice;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getPrice() {
    return price;
  }
  public void setPrice(Double price) {
    this.price = price;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getShippingItemId() {
    return shippingItemId;
  }
  public void setShippingItemId(Integer shippingItemId) {
    this.shippingItemId = shippingItemId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSku() {
    return sku;
  }
  public void setSku(String sku) {
    this.sku = sku;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getTaxable() {
    return taxable;
  }
  public void setTaxable(Boolean taxable) {
    this.taxable = taxable;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getVendorId() {
    return vendorId;
  }
  public void setVendorId(Integer vendorId) {
    this.vendorId = vendorId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getVendorName() {
    return vendorName;
  }
  public void setVendorName(String vendorName) {
    this.vendorName = vendorName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CartShippingOption cartShippingOption = (CartShippingOption) o;
    return (this.currencyCode == null ? cartShippingOption.currencyCode == null : this.currencyCode.equals(cartShippingOption.currencyCode)) &&
        (this.description == null ? cartShippingOption.description == null : this.description.equals(cartShippingOption.description)) &&
        (this.name == null ? cartShippingOption.name == null : this.name.equals(cartShippingOption.name)) &&
        (this.originalPrice == null ? cartShippingOption.originalPrice == null : this.originalPrice.equals(cartShippingOption.originalPrice)) &&
        (this.price == null ? cartShippingOption.price == null : this.price.equals(cartShippingOption.price)) &&
        (this.shippingItemId == null ? cartShippingOption.shippingItemId == null : this.shippingItemId.equals(cartShippingOption.shippingItemId)) &&
        (this.sku == null ? cartShippingOption.sku == null : this.sku.equals(cartShippingOption.sku)) &&
        (this.taxable == null ? cartShippingOption.taxable == null : this.taxable.equals(cartShippingOption.taxable)) &&
        (this.vendorId == null ? cartShippingOption.vendorId == null : this.vendorId.equals(cartShippingOption.vendorId)) &&
        (this.vendorName == null ? cartShippingOption.vendorName == null : this.vendorName.equals(cartShippingOption.vendorName));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.currencyCode == null ? 0: this.currencyCode.hashCode());
    result = 31 * result + (this.description == null ? 0: this.description.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.originalPrice == null ? 0: this.originalPrice.hashCode());
    result = 31 * result + (this.price == null ? 0: this.price.hashCode());
    result = 31 * result + (this.shippingItemId == null ? 0: this.shippingItemId.hashCode());
    result = 31 * result + (this.sku == null ? 0: this.sku.hashCode());
    result = 31 * result + (this.taxable == null ? 0: this.taxable.hashCode());
    result = 31 * result + (this.vendorId == null ? 0: this.vendorId.hashCode());
    result = 31 * result + (this.vendorName == null ? 0: this.vendorName.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CartShippingOption {\n");
    
    sb.append("  currencyCode: ").append(currencyCode).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  originalPrice: ").append(originalPrice).append("\n");
    sb.append("  price: ").append(price).append("\n");
    sb.append("  shippingItemId: ").append(shippingItemId).append("\n");
    sb.append("  sku: ").append(sku).append("\n");
    sb.append("  taxable: ").append(taxable).append("\n");
    sb.append("  vendorId: ").append(vendorId).append("\n");
    sb.append("  vendorName: ").append(vendorName).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
