/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.knetikcloud.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class CountryTaxResource {
  
  @SerializedName("country_iso3")
  private String countryIso3 = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("rate")
  private Double rate = null;
  @SerializedName("tax_shipping")
  private Boolean taxShipping = null;

  /**
   * The iso3 code of the country, cannot be changed
   **/
  @ApiModelProperty(required = true, value = "The iso3 code of the country, cannot be changed")
  public String getCountryIso3() {
    return countryIso3;
  }
  public void setCountryIso3(String countryIso3) {
    this.countryIso3 = countryIso3;
  }

  /**
   * The name of the tax
   **/
  @ApiModelProperty(required = true, value = "The name of the tax")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   * The tax rate as a percentage to a maximum of two decimal places (1.5 means 1.5%)
   **/
  @ApiModelProperty(required = true, value = "The tax rate as a percentage to a maximum of two decimal places (1.5 means 1.5%)")
  public Double getRate() {
    return rate;
  }
  public void setRate(Double rate) {
    this.rate = rate;
  }

  /**
   * Whether the tax applies to shipping costs
   **/
  @ApiModelProperty(required = true, value = "Whether the tax applies to shipping costs")
  public Boolean getTaxShipping() {
    return taxShipping;
  }
  public void setTaxShipping(Boolean taxShipping) {
    this.taxShipping = taxShipping;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CountryTaxResource countryTaxResource = (CountryTaxResource) o;
    return (this.countryIso3 == null ? countryTaxResource.countryIso3 == null : this.countryIso3.equals(countryTaxResource.countryIso3)) &&
        (this.name == null ? countryTaxResource.name == null : this.name.equals(countryTaxResource.name)) &&
        (this.rate == null ? countryTaxResource.rate == null : this.rate.equals(countryTaxResource.rate)) &&
        (this.taxShipping == null ? countryTaxResource.taxShipping == null : this.taxShipping.equals(countryTaxResource.taxShipping));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.countryIso3 == null ? 0: this.countryIso3.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.rate == null ? 0: this.rate.hashCode());
    result = 31 * result + (this.taxShipping == null ? 0: this.taxShipping.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CountryTaxResource {\n");
    
    sb.append("  countryIso3: ").append(countryIso3).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  rate: ").append(rate).append("\n");
    sb.append("  taxShipping: ").append(taxShipping).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
