/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.knetikcloud.model;

import com.knetikcloud.model.ExpressionResource;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class GlobalCheckAndIncrementResource {
  
  @SerializedName("check_value_resource")
  private ExpressionResource checkValueResource = null;
  @SerializedName("global_resource")
  private ExpressionResource globalResource = null;
  @SerializedName("type")
  private String type = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public ExpressionResource getCheckValueResource() {
    return checkValueResource;
  }
  public void setCheckValueResource(ExpressionResource checkValueResource) {
    this.checkValueResource = checkValueResource;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ExpressionResource getGlobalResource() {
    return globalResource;
  }
  public void setGlobalResource(ExpressionResource globalResource) {
    this.globalResource = globalResource;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GlobalCheckAndIncrementResource globalCheckAndIncrementResource = (GlobalCheckAndIncrementResource) o;
    return (this.checkValueResource == null ? globalCheckAndIncrementResource.checkValueResource == null : this.checkValueResource.equals(globalCheckAndIncrementResource.checkValueResource)) &&
        (this.globalResource == null ? globalCheckAndIncrementResource.globalResource == null : this.globalResource.equals(globalCheckAndIncrementResource.globalResource)) &&
        (this.type == null ? globalCheckAndIncrementResource.type == null : this.type.equals(globalCheckAndIncrementResource.type));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.checkValueResource == null ? 0: this.checkValueResource.hashCode());
    result = 31 * result + (this.globalResource == null ? 0: this.globalResource.hashCode());
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GlobalCheckAndIncrementResource {\n");
    
    sb.append("  checkValueResource: ").append(checkValueResource).append("\n");
    sb.append("  globalResource: ").append(globalResource).append("\n");
    sb.append("  type: ").append(type).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
