/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.knetikcloud.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class IOConfig {
  
  @SerializedName("customer")
  private String customer = null;
  @SerializedName("enabled")
  private Boolean enabled = null;
  @SerializedName("environment")
  private String environment = null;
  @SerializedName("product")
  private String product = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCustomer() {
    return customer;
  }
  public void setCustomer(String customer) {
    this.customer = customer;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getEnabled() {
    return enabled;
  }
  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEnvironment() {
    return environment;
  }
  public void setEnvironment(String environment) {
    this.environment = environment;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getProduct() {
    return product;
  }
  public void setProduct(String product) {
    this.product = product;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IOConfig iOConfig = (IOConfig) o;
    return (this.customer == null ? iOConfig.customer == null : this.customer.equals(iOConfig.customer)) &&
        (this.enabled == null ? iOConfig.enabled == null : this.enabled.equals(iOConfig.enabled)) &&
        (this.environment == null ? iOConfig.environment == null : this.environment.equals(iOConfig.environment)) &&
        (this.product == null ? iOConfig.product == null : this.product.equals(iOConfig.product));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.customer == null ? 0: this.customer.hashCode());
    result = 31 * result + (this.enabled == null ? 0: this.enabled.hashCode());
    result = 31 * result + (this.environment == null ? 0: this.environment.hashCode());
    result = 31 * result + (this.product == null ? 0: this.product.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class IOConfig {\n");
    
    sb.append("  customer: ").append(customer).append("\n");
    sb.append("  enabled: ").append(enabled).append("\n");
    sb.append("  environment: ").append(environment).append("\n");
    sb.append("  product: ").append(product).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
