/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.knetikcloud.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class RewardCurrencyResource {
  
  @SerializedName("currency_code")
  private String currencyCode = null;
  @SerializedName("currency_name")
  private String currencyName = null;
  @SerializedName("max_rank")
  private Integer maxRank = null;
  @SerializedName("min_rank")
  private Integer minRank = null;
  @SerializedName("percent")
  private Boolean percent = null;
  @SerializedName("value")
  private Double value = null;

  /**
   * The code of the currency type to give
   **/
  @ApiModelProperty(required = true, value = "The code of the currency type to give")
  public String getCurrencyCode() {
    return currencyCode;
  }
  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }

  /**
   * The name of the currency reward to give.  Set by currency_code)
   **/
  @ApiModelProperty(value = "The name of the currency reward to give.  Set by currency_code)")
  public String getCurrencyName() {
    return currencyName;
  }
  public void setCurrencyName(String currencyName) {
    this.currencyName = currencyName;
  }

  /**
   * The highest number (worst) rank to give the reward to. Must be greater than or equal to minRank
   **/
  @ApiModelProperty(required = true, value = "The highest number (worst) rank to give the reward to. Must be greater than or equal to minRank")
  public Integer getMaxRank() {
    return maxRank;
  }
  public void setMaxRank(Integer maxRank) {
    this.maxRank = maxRank;
  }

  /**
   * The lowest number (best) rank to give the reward to. Must be greater than zero
   **/
  @ApiModelProperty(required = true, value = "The lowest number (best) rank to give the reward to. Must be greater than zero")
  public Integer getMinRank() {
    return minRank;
  }
  public void setMinRank(Integer minRank) {
    this.minRank = minRank;
  }

  /**
   * True if the value is actually a percentage of the intake
   **/
  @ApiModelProperty(required = true, value = "True if the value is actually a percentage of the intake")
  public Boolean getPercent() {
    return percent;
  }
  public void setPercent(Boolean percent) {
    this.percent = percent;
  }

  /**
   * The amount of currency to give. For percentage values, 0.5 is 50%
   **/
  @ApiModelProperty(required = true, value = "The amount of currency to give. For percentage values, 0.5 is 50%")
  public Double getValue() {
    return value;
  }
  public void setValue(Double value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RewardCurrencyResource rewardCurrencyResource = (RewardCurrencyResource) o;
    return (this.currencyCode == null ? rewardCurrencyResource.currencyCode == null : this.currencyCode.equals(rewardCurrencyResource.currencyCode)) &&
        (this.currencyName == null ? rewardCurrencyResource.currencyName == null : this.currencyName.equals(rewardCurrencyResource.currencyName)) &&
        (this.maxRank == null ? rewardCurrencyResource.maxRank == null : this.maxRank.equals(rewardCurrencyResource.maxRank)) &&
        (this.minRank == null ? rewardCurrencyResource.minRank == null : this.minRank.equals(rewardCurrencyResource.minRank)) &&
        (this.percent == null ? rewardCurrencyResource.percent == null : this.percent.equals(rewardCurrencyResource.percent)) &&
        (this.value == null ? rewardCurrencyResource.value == null : this.value.equals(rewardCurrencyResource.value));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.currencyCode == null ? 0: this.currencyCode.hashCode());
    result = 31 * result + (this.currencyName == null ? 0: this.currencyName.hashCode());
    result = 31 * result + (this.maxRank == null ? 0: this.maxRank.hashCode());
    result = 31 * result + (this.minRank == null ? 0: this.minRank.hashCode());
    result = 31 * result + (this.percent == null ? 0: this.percent.hashCode());
    result = 31 * result + (this.value == null ? 0: this.value.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class RewardCurrencyResource {\n");
    
    sb.append("  currencyCode: ").append(currencyCode).append("\n");
    sb.append("  currencyName: ").append(currencyName).append("\n");
    sb.append("  maxRank: ").append(maxRank).append("\n");
    sb.append("  minRank: ").append(minRank).append("\n");
    sb.append("  percent: ").append(percent).append("\n");
    sb.append("  value: ").append(value).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
