/*
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.knetikcloud.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import android.os.Parcelable;
import android.os.Parcel;

/**
 * SimpleReferenceResourceint
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-17T08:21:48.548-04:00")
public class SimpleReferenceResourceint implements Parcelable {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  public SimpleReferenceResourceint id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * The id of the referenced object
   * @return id
  **/
  @ApiModelProperty(example = "null", required = true, value = "The id of the referenced object")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

   /**
   * The name of the referenced object
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "The name of the referenced object")
  public String getName() {
    return name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SimpleReferenceResourceint simpleReferenceResourceint = (SimpleReferenceResourceint) o;
    return Objects.equals(this.id, simpleReferenceResourceint.id) &&
        Objects.equals(this.name, simpleReferenceResourceint.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SimpleReferenceResourceint {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
  public void writeToParcel(Parcel out, int flags) {
     
    out.writeValue(id);

    out.writeValue(name);
  }

  public SimpleReferenceResourceint() {
    super();
  }

  SimpleReferenceResourceint(Parcel in) {
    
    id = (Integer)in.readValue(null);
    name = (String)in.readValue(null);
  }
  
  public int describeContents() {
    return 0;
  }

  public static final Parcelable.Creator<SimpleReferenceResourceint> CREATOR = new Parcelable.Creator<SimpleReferenceResourceint>() {
    public SimpleReferenceResourceint createFromParcel(Parcel in) {
      return new SimpleReferenceResourceint(in);
    }
    public SimpleReferenceResourceint[] newArray(int size) {
      return new SimpleReferenceResourceint[size];
    }
  };
}

