/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.knetikcloud.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class StripeCreatePaymentMethod {
  
  @SerializedName("token")
  private String token = null;
  @SerializedName("user_id")
  private Integer userId = null;

  /**
   * A token from Stripe to identify payment info to be tied to the customer
   **/
  @ApiModelProperty(required = true, value = "A token from Stripe to identify payment info to be tied to the customer")
  public String getToken() {
    return token;
  }
  public void setToken(String token) {
    this.token = token;
  }

  /**
   * The id of the user, if null the logged in user is used. Admin privilege need to specify other users
   **/
  @ApiModelProperty(value = "The id of the user, if null the logged in user is used. Admin privilege need to specify other users")
  public Integer getUserId() {
    return userId;
  }
  public void setUserId(Integer userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StripeCreatePaymentMethod stripeCreatePaymentMethod = (StripeCreatePaymentMethod) o;
    return (this.token == null ? stripeCreatePaymentMethod.token == null : this.token.equals(stripeCreatePaymentMethod.token)) &&
        (this.userId == null ? stripeCreatePaymentMethod.userId == null : this.userId.equals(stripeCreatePaymentMethod.userId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.token == null ? 0: this.token.hashCode());
    result = 31 * result + (this.userId == null ? 0: this.userId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class StripeCreatePaymentMethod {\n");
    
    sb.append("  token: ").append(token).append("\n");
    sb.append("  userId: ").append(userId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
