/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.knetikcloud.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class UserActivityResultsResource {
  
  @SerializedName("score")
  private Long score = null;
  @SerializedName("tags")
  private List<String> tags = null;
  @SerializedName("user_id")
  private Integer userId = null;

  /**
   * The raw score. Null means non-compete or disqualification
   **/
  @ApiModelProperty(value = "The raw score. Null means non-compete or disqualification")
  public Long getScore() {
    return score;
  }
  public void setScore(Long score) {
    this.score = score;
  }

  /**
   * Any tags for the metric. Each unique tag will translate into a unique leaderboard. Maximum 5 tags and 50 characters each
   **/
  @ApiModelProperty(value = "Any tags for the metric. Each unique tag will translate into a unique leaderboard. Maximum 5 tags and 50 characters each")
  public List<String> getTags() {
    return tags;
  }
  public void setTags(List<String> tags) {
    this.tags = tags;
  }

  /**
   * The id of the player
   **/
  @ApiModelProperty(required = true, value = "The id of the player")
  public Integer getUserId() {
    return userId;
  }
  public void setUserId(Integer userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserActivityResultsResource userActivityResultsResource = (UserActivityResultsResource) o;
    return (this.score == null ? userActivityResultsResource.score == null : this.score.equals(userActivityResultsResource.score)) &&
        (this.tags == null ? userActivityResultsResource.tags == null : this.tags.equals(userActivityResultsResource.tags)) &&
        (this.userId == null ? userActivityResultsResource.userId == null : this.userId.equals(userActivityResultsResource.userId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.score == null ? 0: this.score.hashCode());
    result = 31 * result + (this.tags == null ? 0: this.tags.hashCode());
    result = 31 * result + (this.userId == null ? 0: this.userId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserActivityResultsResource {\n");
    
    sb.append("  score: ").append(score).append("\n");
    sb.append("  tags: ").append(tags).append("\n");
    sb.append("  userId: ").append(userId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
