/**
 * Knetik Platform API Documentation Latest
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class AchievementProgressUpdateRequest {
  
  @SerializedName("increment_value")
  private Boolean incrementValue = null;
  @SerializedName("progress_value")
  private Integer progressValue = null;

  /**
   * Whether to add one to the current progress instead of setting it to progress_value. Default: false
   **/
  @ApiModelProperty(value = "Whether to add one to the current progress instead of setting it to progress_value. Default: false")
  public Boolean getIncrementValue() {
    return incrementValue;
  }
  public void setIncrementValue(Boolean incrementValue) {
    this.incrementValue = incrementValue;
  }

  /**
   * The amount of progress towards earning the achievement. The max/target depends on the achievement. Required if increment_value is false/missing.
   **/
  @ApiModelProperty(value = "The amount of progress towards earning the achievement. The max/target depends on the achievement. Required if increment_value is false/missing.")
  public Integer getProgressValue() {
    return progressValue;
  }
  public void setProgressValue(Integer progressValue) {
    this.progressValue = progressValue;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AchievementProgressUpdateRequest achievementProgressUpdateRequest = (AchievementProgressUpdateRequest) o;
    return (this.incrementValue == null ? achievementProgressUpdateRequest.incrementValue == null : this.incrementValue.equals(achievementProgressUpdateRequest.incrementValue)) &&
        (this.progressValue == null ? achievementProgressUpdateRequest.progressValue == null : this.progressValue.equals(achievementProgressUpdateRequest.progressValue));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.incrementValue == null ? 0: this.incrementValue.hashCode());
    result = 31 * result + (this.progressValue == null ? 0: this.progressValue.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AchievementProgressUpdateRequest {\n");
    
    sb.append("  incrementValue: ").append(incrementValue).append("\n");
    sb.append("  progressValue: ").append(progressValue).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
