/**
 * Knetik Platform API Documentation Latest
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class UserBaseResource {
  
  @SerializedName("avatar_url")
  private String avatarUrl = null;
  @SerializedName("display_name")
  private String displayName = null;
  @SerializedName("email")
  private String email = null;
  @SerializedName("fullname")
  private String fullname = null;
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("username")
  private String username = null;

  /**
   * The url of the user's avatar image
   **/
  @ApiModelProperty(value = "The url of the user's avatar image")
  public String getAvatarUrl() {
    return avatarUrl;
  }
  public void setAvatarUrl(String avatarUrl) {
    this.avatarUrl = avatarUrl;
  }

  /**
   * The chosen display name of the user, defaults to username if not present
   **/
  @ApiModelProperty(value = "The chosen display name of the user, defaults to username if not present")
  public String getDisplayName() {
    return displayName;
  }
  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  /**
   * The user's email address (private). May be required and/or unique depending on system configuration (both on by default). Must match standard email requirements if provided (RFC 2822)
   **/
  @ApiModelProperty(required = true, value = "The user's email address (private). May be required and/or unique depending on system configuration (both on by default). Must match standard email requirements if provided (RFC 2822)")
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   * The user's full name (private)
   **/
  @ApiModelProperty(value = "The user's full name (private)")
  public String getFullname() {
    return fullname;
  }
  public void setFullname(String fullname) {
    this.fullname = fullname;
  }

  /**
   * The id of the user
   **/
  @ApiModelProperty(value = "The id of the user")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * The login username for the user (private). May be set to match email if system does not require usernames separately.
   **/
  @ApiModelProperty(required = true, value = "The login username for the user (private). May be set to match email if system does not require usernames separately.")
  public String getUsername() {
    return username;
  }
  public void setUsername(String username) {
    this.username = username;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserBaseResource userBaseResource = (UserBaseResource) o;
    return (this.avatarUrl == null ? userBaseResource.avatarUrl == null : this.avatarUrl.equals(userBaseResource.avatarUrl)) &&
        (this.displayName == null ? userBaseResource.displayName == null : this.displayName.equals(userBaseResource.displayName)) &&
        (this.email == null ? userBaseResource.email == null : this.email.equals(userBaseResource.email)) &&
        (this.fullname == null ? userBaseResource.fullname == null : this.fullname.equals(userBaseResource.fullname)) &&
        (this.id == null ? userBaseResource.id == null : this.id.equals(userBaseResource.id)) &&
        (this.username == null ? userBaseResource.username == null : this.username.equals(userBaseResource.username));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.avatarUrl == null ? 0: this.avatarUrl.hashCode());
    result = 31 * result + (this.displayName == null ? 0: this.displayName.hashCode());
    result = 31 * result + (this.email == null ? 0: this.email.hashCode());
    result = 31 * result + (this.fullname == null ? 0: this.fullname.hashCode());
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.username == null ? 0: this.username.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserBaseResource {\n");
    
    sb.append("  avatarUrl: ").append(avatarUrl).append("\n");
    sb.append("  displayName: ").append(displayName).append("\n");
    sb.append("  email: ").append(email).append("\n");
    sb.append("  fullname: ").append(fullname).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  username: ").append(username).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
